# nnU-Net v2 Conda environment
#
# Notes:
# - Default config installs GPU-enabled PyTorch (CUDA 12.1). If you need CPU-only,
#   comment out the `pytorch-cuda` line and add `cpuonly` to dependencies.
# - Python 3.10 is chosen for broad compatibility with nnU-Net v2.
# - Most scientific libs come from conda; remaining packages are installed via pip.

name: seg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  # Core scientific stack from conda (fast, compiled builds)
  - numpy>=1.24
  - scipy
  - scikit-learn
  - scikit-image>=0.19.3
  - simpleitk>=2.2.1
  - pandas
  - matplotlib
  - seaborn
  - imagecodecs
  - tifffile
  - nibabel
  - yacs
  - graphviz            # graphviz binaries
  - python-graphviz     # python bindings to graphviz
  - tqdm
  - requests

  # pip packages (GPU PyTorch cu126 and pip-only libs)
  - pip:
      # Use NVIDIA GPU build for PyTorch matching your driver (CUDA 12.7 capable)
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch==2.7.1+cu126
      - torchvision==0.22.1+cu126
      - triton==3.3.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77

      # Install this repo in editable mode
      - -e .

      # Explicit dependencies aligned with pyproject.toml
      - acvl-utils>=0.2.3,<0.3
      - dynamic-network-architectures>=0.4.1,<0.5
      - batchgenerators>=0.25.1
      - batchgeneratorsv2>=0.3.0
      - einops
      - blosc2>=3.0.0b1
      # Additional libraries observed in seg environment
      - argparse==1.4.0
      - connected-components-3d==3.24.0
      - fft-conv-pytorch==1.2.0
      - filelock==3.19.1
      - fsspec==2025.9.0
      - future==1.0.0
      - hf-xet==1.1.10
      - hiddenlayer==0.3
      - huggingface-hub==0.34.4
      - jinja2==3.1.6
      - linecache2==1.0.0
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - ndindex==1.10.0
      - numexpr==2.12.1
      - platformdirs==4.4.0
      - py-cpuinfo==9.0.0
      - safetensors==0.6.2
      - sympy==1.14.0
      - timm==1.0.19
      - traceback2==1.4.0
      - unittest2==1.1.0
